# This is a basic workflow to help you get started with Actions

name: 🚀 Upload new version of Tarot app on FTP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
              
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: b2.hitrost.net
        username: concepts-home@2gika.si
        password: ${{ secrets.FTP_PASSWORD }}
        port: 6021
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          tailwind.config.js
          package-lock.json
          .babelrc
          **/src*/**
          **/workflows/**
          .gitignore
          LICENCE
